spring:

  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true # 콘솔에서 sql 문이 좀더 보기 좋게 나오게 해줌.
    generate-ddl: true
    defer-datasource-initialization: true # 스프링부트 2.5 버전 이상부터는 하이버네이트가 초기화 되기 전에 data.sql이 먼저 실행 되므로 이설정을 해주지 않으면 테이블을 생성하기 전에 쿼리문이 실행되어 에러가 반환됨.

# mysql db
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root


# maria db
#  datasource:
#    url: jdbc:mariadb://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
#    username: root
#    password: root

server:
  port: 8080